name: CI

on:
  push:
    branches: [ main, 134-macos-support ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: 'Set version number in package.json'
        run: |
          echo "Runner OS: $RUNNER_OS"
          if [ "$RUNNER_OS" == "macOS" ]; then
            sed -i '' 's/0.0.1/${{ env.GitVersion_SemVer }}/' package.json
          else
            sed -i 's/0.0.1/${{ env.GitVersion_SemVer }}/' package.json
          fi
      - name: Install Dependencies
        run: npm clean-install

      - name: Publish
        run: npm run publish
