name: CI

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@main

      - name: 'Set version number in package.json (MacOS)'
        if: runner.os == 'macOS'
        run: sed -i '' 's/0.0.1/${{ env.GitVersion_SemVer }}/' package.json
      
      - name: 'Set version number in package.json (non-MacOS)'
        if: runner.os != 'macOS'
        run: sed -i 's/0.0.1/${{ env.GitVersion_SemVer }}/' package.json
        
      - name: Install Dependencies 1/2
        run: npm clean-install

      - name: Install Dependencies 2/2
        run: pip install setuptools

      - name: Publish
        run: npm run publish
