name: CI

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v4

      - name: 'Set version number in package.json (MacOS)'
        if: runner.os == 'macOS'
        run: sed -i '' 's/0.0.1/${{ env.GitVersion_SemVer }}/' package.json
      
      - name: 'Set version number in package.json (non-MacOS)'
        if: runner.os != 'macOS'
        run: sed -i 's/0.0.1/${{ env.GitVersion_SemVer }}/' package.json

      - name: Install Dependencies
        run: |
          pip install --upgrade setuptools
          pip install wheel
          npm clean-install

      - name: Publish
        run: npm run publish
